server:
  session:
    timeout: 30000

---
#  ˝æ›ø‚≈‰÷√ #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lesson_choice?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1949
    driverClassName: com.mysql.jdbc.Driver

---
# Mybatis ≈‰÷√ #
mybatis:
  typeAliasesPackage: com.mcl.bysj.entity
  mapperLocations: classpath:mapper/*.xml

---
# πÿ±’thymeleafƒ£∞Âª∫¥Ê #
spring:
  thymeleaf:
    cache: false